# Header
menu:
  Главная: /
  Архив: /archives
rss: /atom.xml

# Content
excerpt_link: Читать Далее
fancybox: true

# Sidebar
sidebar: right
widgets:
- tagcloud
#- tag
- category
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
yandex_metrika:

favicon: /favicon.ico
twitter: krasovsky_s
google_plus:
fb_admins:
fb_app_id:

vk: lord.protector
tg: kraso
gh: Lord-Protector
